### ISSUE TITLE
change routing for better compatibility with dash workspaces

### ISSUE THREAD

**Issue by e-wallace** [dkedar7/fast_dash#39]
* Fast Dash version: 0.2.6
* Python version: 3.9
* Operating System:

### Description

Currently, fast-dash is not compatible with dash_proxy. 
Workspaces (Dash IDE) apps can only be run in the default port (8050). When you try to use the fast_dash package in the Dash IDE, the web app will not render due to a port issue. The issue persists even when you specify the port like so: ```@fastdash(port=8050)```

### What I Did
Modify the routing code in fast dash to allow use of dash proxy ( and compatibility with Dash IDE)
```
   def run(self):
        #change from self.server to self.app
        self.app.run(  
            **self.run_kwargs
        ) if self.mode is None else self.app.run_server(
            mode=self.mode, **self.run_kwargs
        )
```

also allowing gunicorn support benefits users trying to deploy their apps into a production environment.
```
if __name__ == "__main__":
    app.run()
```

**Comment by dkedar7** [comment]
Thanks for the issue @e-wallace. What's the best way to test this edit?
